CREATE DATABASE API_EXEMPLO_DB

USE API_EXEMPLO_DB

CREATE TABLE FER(
	FER_GUID varchar(36) NOT NULL PRIMARY KEY,
	FER_TIPO int NOT NULL,
	FER_DESC varchar(50) NOT NULL,
	FER_DATA date NOT NULL
);

--ALTER TABLE FER ADD  CONSTRAINT DF_FER_FER_GUID  DEFAULT (NEWID()) FOR FER_GUID
